# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/lms_analytics
    depends_on:
      - db
    volumes:
      - ./app:/app/app
      - ./data:/app/data

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=lms_analytics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: